### ISSUE TITLE
Executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by guofengzh** [openpitrix/helm-chart#4]
Following the docs to install openpitrix (using openpitrix-v0.3.5.tar.gz) on an existed k8s cluster using:
    helm install . -n openpitrix --namespace openpitrix-system
The following pods are failed:

openpitrix-vendor-manager-deployment-55b74f6d9c-fx4sc      0/1    CrashLoopBackOff  12        41m
openpitrix-attachment-manager-deployment-77c4cf668-d6rks   0/1    CrashLoopBackOff  12        41m
openpitrix-rp-manager-deployment-56d9bd9759-2gml5          0/1    CrashLoopBackOff  12        41m

The logs:

  Warning  Failed     3m6s (x4 over 4m1s)   kubelet, node4     Error: failed to start container "openpitrix-vendor-manag
er": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "e
xec: \"appvendor-manager\": executable file not found in $PATH": unknown

  Warning  Failed     8m21s (x4 over 9m22s)  kubelet, node4     Error: failed to start container "openpitrix-attachment-
manager": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caus
ed "exec: \"attachment-manager\": executable file not found in $PATH": unknown

  Warning  Failed     13m (x5 over 15m)    kubelet, node2     Error: failed to start container "openpitrix-rp-manager":
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec:
\"runtime-provider-manager\": executable file not found in $PATH": unknown

How to fix it.

Your help is appreciated.

Thanks,

Guofeng

**Comment by yudong2015** [comment]
We will publish the V0.4 of openpitrix/helm-chart at end of the month, above bugs would be fixed; Please test it with V0.4.

**Comment by guofengzh** [comment]
Thanks for your quick response. I will test the new release then.
